### ISSUE TITLE
Clarify relationship to django-webpush app and fix license

### ISSUE THREAD

**Issue by jezdez** [subhajeet2107/django-simplepush#1]
This code base is very similar and in many cases identical to the [django-webpush](https://github.com/safwanrahman/django-webpush) code base. Since django-webpush is published using the [GPL3 license](https://github.com/safwanrahman/django-webpush/blob/master/LICENSE) it is implied that django-simplepush is a modified work of django-webpush and is required to be published under the same license. Currently django-simplepush is licensed under the liberal BSD license which is a violation of the license agreement of django-webpush. Please fix the license of django-simplepush accordingly.

Legal sides aside, I'd like to encourage you to work together with the maintainer of django-webpush (@safwanrahman) to merge your libraries and work together as that would remove the necessity to have a modified library in the first place.

EDIT: a previous version of this issue wrongly used "MIT license" instead of the correct "BSD license" of the django-simplepush library

**Comment by subhajeet2107** [comment]
Hello, thanks for pointing the license issues, i will change the the original GPL3, but i dont think this library can be merged with django-webpush, this was inspired by django webpush and the codebase differs a lot , for eg: jinja2 support, images, custom url support in notifications etc are features which cannot be merged, so i would like to keep this library as a separate project from django webpush, is this fine ? Thanks a lot :)

**Comment by subhajeet2107** [comment]
Updated License, Thanks :)

**Comment by safwanrahman** [comment]
@subhajeet2107 Hey, I am the maintainer of ``django-webpush``. Regarding License, I would like to address that you need mention that django-simplepush is a modified work of django-webpush in your project.
BTW, its your decision to keep this project as separate project but I dont think its not possible to merge the feature you have implemented.
