### ISSUE TITLE
Add defer, or separate tags

### ISSUE THREAD

**Issue by narnikgamarnikus** [subhajeet2107/django-simplepush#2]
Hey.

In order to avoid performance problems due to javascript in the head, it is necessary either to separate the {% simplepush_html %}, where one is  {% simplepush_mets %} and the {% simplepush_js %}, or else change `<script ...> </script>` to `<script defer ...> </script>`

 I can do this for you if you accept my commit.

**Comment by subhajeet2107** [comment]
Hello Thanks for pointing out, please send a pull request with the change
